### ISSUE TITLE
Devtoberfest - Week 2 - Speaker

### ISSUE THREAD

**Issue by jcailan** [SAPDocuments/devtoberfest-2021#1518]
Tutorials: https://developers.sap.com/tutorials/devtoberfest-week-2-speaker.html
--------------------------

Is this Devtoberfest Tutorial doesn't really have the link to the video?

**Comment by qmacro** [comment]
A link to a single video wouldn't make sense - the question is about all three video presentations from David, Andre and me ... and there's a link in the tutorial to take you to the repo which has the relevant page :-)
