### ISSUE TITLE
Devtoberfest - Week 6 - Fun Friday

### ISSUE THREAD

**Issue by softy12** [SAPDocuments/devtoberfest-2021#2414]
Tutorials: https://developers.sap.com/tutorials/devtoberfest-week-6-fun-friday.html
--------------------------

Hello folks, I attended week 6 devtoberfest trivia night on November 12th, 17:00 CET (Berlin). But I do not see a points I marked there at gameboard. I use some nickname at menti.com while submitting my answers. The nickname is different from my SCN's ID.
Was I supposed to use SCN's ID at menti.com?
Is there any chance for me to get those points I scored to the gameboard?

thanks

**Comment by jung-thomas** [comment]
The user that you used on menti.com shouldn't matter. It only matters that you use the same SCN ID to complete the tutorials as what you registered with Devtoberfest for.
